# Generated by Django 5.0.2 on 2024-03-02 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_alter_wallet_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletsHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, verbose_name='Дата перевода')),
                ('money_amount', models.BigIntegerField(default=0, verbose_name='Сумма денег для перевода')),
                ('from_wallet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_wallet', to='wallet.wallet', verbose_name='Кошелёк, откуда перевели')),
                ('to_wallet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_wallet', to='wallet.wallet', verbose_name='Кошелёк, куда перевели')),
            ],
            options={
                'verbose_name': 'История перевода',
                'verbose_name_plural': 'Истории переводов',
                'ordering': ('-created_at',),
            },
        ),
    ]
