# Generated by Django 5.0.2 on 2024-03-02 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_walletshistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletshistory',
            name='created_at',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='Дата перевода'),
        ),
        migrations.AlterField(
            model_name='walletshistory',
            name='from_wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_wallet', to='wallet.wallet', verbose_name='Кошелёк, откуда переводить'),
        ),
        migrations.AlterField(
            model_name='walletshistory',
            name='to_wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_wallet', to='wallet.wallet', verbose_name='Кошелёк, куда переводить'),
        ),
    ]
