# Generated by Django 5.0.2 on 2024-03-02 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_alter_walletshistory_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletshistory',
            name='currency',
            field=models.CharField(choices=[('RUB', 'Рубль'), ('USD', 'Доллaр')], default='RUB', verbose_name='Валюта хранения'),
        ),
    ]
