# Generated by Django 5.0.2 on 2024-03-02 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_walletshistory_currency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallet',
            options={'ordering': ('owner', 'currency'), 'verbose_name': 'Кошелёк', 'verbose_name_plural': 'Кошельки'},
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='user',
            new_name='owner',
        ),
    ]
