# Generated by Django 5.0.2 on 2024-03-02 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_alter_wallet_options_rename_user_wallet_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='money_amount',
            new_name='balance',
        ),
        migrations.RenameField(
            model_name='walletshistory',
            old_name='money_amount',
            new_name='balance',
        ),
    ]
